version: '3.8'

services:
  postgres:
    container_name: creativeLabel_opd_project_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - creativeLabel_opd_project_volume:/var/lib/postgresql/data
      - ./develop/app/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - internal

  app:
    container_name: creativeLabel_opd_project_app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - internal

volumes:
  creativeLabel_opd_project_volume:

networks:
  internal:
    name: internal